### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by elgs** [nickvellios/gojwt#1]
1. can the claims type be changed from map[string]string to map[string]interface{}?
2. does this library support verify? It seems I didn't see anything in the code.

**Comment by elgs** [comment]
Looking into the code. I found the secret was generated by the claim itself and a salt. I'm not sure if I misunderstood it or not, but I think if this is the case, there is a problem. How would the server know a jwt token is signed by the sever or anyone else?

**Comment by nickvellios** [comment]
Sorry, I just saw this now.  You can update the salt to anything you want.  In my use case, a random salt generated at the launch of the process was sufficient.  There are better, more robust libraries for JWT and I'd recommend using one of them at this point.

https://github.com/nickvellios/gojwt/blob/8d290ff0931c0aa5c0be29e072f499723e82cf7f/jwt.go#L56
